### ISSUE TITLE
 台球阴影问题

### ISSUE THREAD

**Issue by WangQAQ** [cheesestudio/VRChat-Pool-table-15-red-snooker-Pyramid-Chinese-8-MS-VRCSA-Billiards#2]
# 台球阴影渲染队列优化
---
### 下图中展示了台球阴影穿过菜单的画面，此时渲染队列如下 2000(不透明（台球桌））-> 2450(半透明) -> 3000(菜单) -> 3006(台球阴影) 此时最后渲染的阴影会覆盖位于前面的菜单故此造成阴影“穿透菜单”
![1](https://github.com/user-attachments/assets/0d60e410-fdf1-4c7a-be92-444dec278789)
### 修改后成为 2000(不透明（台球桌））-> 2450(半透明(台球阴影)) -> 3000(菜单) 此时菜单于阴影后刷新且不会穿透台球等问题（暂时没发现）
![2](https://github.com/user-attachments/assets/0b0b4b41-3024-4185-b75e-dbfe7445e82d)
### 修改位置
![3](https://github.com/user-attachments/assets/71a9dca4-a509-4c7b-b4fe-ebb7468f1d45)

**Comment by cheesestudio** [comment]
太强啦
